webtalk_init -webtalk_dir C:/Users/DELL/Desktop/2024170/thinpad_top.sim/sim_1/synth/timing/xsim/xsim.dir/tb_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 27 17:36:03 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1bd39b33-a691-45a1-b52f-e4a505b5d824" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e0777dd008c45fcbaffd6b18f2c35e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2918 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3406593 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "174388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2960294821 -regid "" -xml C:/Users/DELL/Desktop/2024170/thinpad_top.sim/sim_1/synth/timing/xsim/xsim.dir/tb_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/DELL/Desktop/2024170/thinpad_top.sim/sim_1/synth/timing/xsim/xsim.dir/tb_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/DELL/Desktop/2024170/thinpad_top.sim/sim_1/synth/timing/xsim/xsim.dir/tb_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
